name: KaBan
main: guru.haun.kaBan.KaBanPlugin
version: 0.0.0
commands:
    kaban:
        description: The base command for KaBan
        usage: /<command> help
        aliases: [k,kb,kab,kban]
 permissions:
     kaban.help:
         default: op
