name: KaBan
main: guru.haun.kaban.KaBan
version: 0.0.0
commands:
    kaban:
        description: The base command for KaBan
        usage: /<command> help
        aliases: [kban,kab,kb,k]
permissions:
    kaban.about:
        description: See the about message for KaBan
        default: op